pipeline:
  docker:
    image: plugins/docker
    repo: registry-testing.kuainiujinke.com/drone-test
    registry: registry-testing.kuainiujinke.com
    tags: latest
    dockerfile: Dockerfile  

  slack:
    image: plugins/slack
    webhook: http://119.28.25.121:3000
    channel: dev
    template: >
      {"status": {{ build.status }}, "branch": {{ build.branch}}, "tag": {{ build.tag }}}
    when:
      status: [ success, failure ]
